### ISSUE TITLE
E-mail sent to default address instead of the specified

### ISSUE THREAD

**Issue by CptCharlesG** [yireo/Yireo_TaxRatesManager2#3]
A small problem:
Even if I set a different e-mail address is specified in the settings, the notification e-mail is being sent to the default address.

Also, minor feedback: is the cron supposed to run every 3 minutes? Personally I changed it to run once a day.

**Comment by jissereitsma** [comment]
Thanks. This seemed to a stupid bug that nobody noticed yet. It is fixed in the newest version 1.2.10.

As for the cron timing. Yes, 3 minutes seems a bit much. But technically, once a VAT percentage changes, you are obliged to react as soon as possible. So every order that comes in after 00:00:01 on New Years Eve is risky.

Note that you can change this by just duplicating the `crontab.xml` in a custom module.

Thanks for the reporting!

I'm closing the issue, but let me know if anything is up.
